sudo: required

services:
 - docker

language: go

go:
  - 1.9.x
  - master

env:
  global:
    - DGRAPH_ADDR=127.0.0.1:9080
  matrix:
    - DGVERSION=v0.8.1
    - DGVERSION=master

matrix:
  allow_failures:
    - go: master
    - env: DGVERSION=master

before_install:
  - docker pull dgraph/dgraph:$DGVERSION
  - docker run -d -p 127.0.0.1:9080:9080 --name dgraph-$DGVERSION dgraph/dgraph:$DGVERSION dgraph --bindall=true --memory_mb 2048
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure

before_script:
  - sleep 5

script:
  - go vet ./...
  - go test -race -v ./...

after_script:
  - docker rm -f dgraph-$DGVERSION