sudo: required

language: go

go:
  - 1.9.x
  - master

services:
 - docker

env:
  global:
    DGRAPH_ADDR=127.0.0.1:9090
  matrix:
    DGVERSION=latest
    DGVERSION=v0.8.1

before_install:
  - docker pull dgraph/dgraph:$DGVERSION
  - docker run -d -p 127.0.0.1:9090:9090 --name dgraph dgraph/dgraph:$DGVERSION dgraph --bindall=true --memory_mb 1024
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure

script:
  - go vet ./...
  - go test -race -v ./...

after_script:
  - docker rm -f dgraph