
version: '3'

services: 
  dgraph:
    image: dgraph/dgraph:v0.8.1
    command: dgraph --bindall=true --memory_mb 1025
    ports:
      - 8080
      - 9080
    volumes:
      - ./.data/dgraph:/dgraph